# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonvale', '0002_auto_20170607_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': '1. ElementTypes',
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name_plural': '2. Currencies'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['name', 'element_type'], 'verbose_name_plural': '3. Elements'},
        ),
        migrations.AlterModelOptions(
            name='habitat',
            options={'ordering': ['name', 'element', 'dragon_capacity', 'coffer_currency', 'length', 'width', 'cost_currency', 'cost', 'build_time'], 'verbose_name_plural': '5. Habitats'},
        ),
        migrations.AlterModelOptions(
            name='island',
            options={'ordering': ['name', 'cost_currency', 'cost', 'level_available', 'summon_time'], 'verbose_name_plural': '4. Islands'},
        ),
        migrations.AlterField(
            model_name='habitat',
            name='coffer_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffer_currencies', to='dragonvale.Currency'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='cost_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_currencies', to='dragonvale.Currency'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonvale.Element'),
        ),
        migrations.AlterField(
            model_name='island',
            name='cost_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonvale.Currency'),
        ),
        migrations.AddField(
            model_name='element',
            name='element_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonvale.ElementType'),
        ),
    ]
