# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonvale', '0003_auto_20170608_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['name', 'element_type', 'opposite_element_type'], 'verbose_name_plural': '3. Elements'},
        ),
        migrations.AddField(
            model_name='element',
            name='opposite_element_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opposite_element_types', to='dragonvale.ElementType'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_types', to='dragonvale.ElementType'),
        ),
    ]
